### ISSUE TITLE
Não estou conseguindo editar produtos

### ISSUE THREAD

**Issue by luizcn** [tiagocordeiro/nfimport#308]

**Comment by luizcn** [comment]
Quando clico em "Atualizar" nada acontece.

**Comment by tiagocordeiro** [comment]
Acho que sei o que pode ser, vou testar. Aparentemente os produtos importados do Bling estão sem PK/ID

**Comment by tiagocordeiro** [comment]
Na verdade, parece ser os campos obrigatórios do formulário que estão na primeira aba (Informações), como a mensagem só aparece no campo, pode parecer que não aconteceu nada.
Vou criar uma branche com essa issue pra resolver isso.
